-- =========================================================
-- Supabase setup for concert-site
-- Safe browser architecture:
--   bookings        = private personal data
--   reserved_seats  = public seat occupancy + Realtime
--   donation_intents = click/intention log, NOT confirmed payments
-- =========================================================

create extension if not exists pgcrypto;

-- ---------- TABLES ----------
create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(full_name) between 2 and 160),
  phone text not null check (char_length(phone) between 5 and 40),
  email text not null check (char_length(email) between 5 and 254),
  created_at timestamptz not null default now()
);

create table if not exists public.reserved_seats (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  sector text not null check (sector in ('Сцена', 'Зал', 'Пульт', 'Балкон') or sector like 'Балкон %'),
  row_num integer not null check (row_num between 1 and 50),
  seat_num integer not null check (seat_num between 1 and 100),
  status text not null default 'booked' check (status = 'booked'),
  created_at timestamptz not null default now(),
  constraint reserved_seats_one_place unique (sector, row_num, seat_num)
);

create table if not exists public.donation_intents (
  id uuid primary key default gen_random_uuid(),
  donor_name text,
  amount numeric(12,2) not null check (amount >= 50),
  message text,
  created_at timestamptz not null default now()
);

-- ---------- RLS ----------
alter table public.bookings enable row level security;
alter table public.reserved_seats enable row level security;
alter table public.donation_intents enable row level security;

-- Start from least privilege.
revoke all on table public.bookings from anon, authenticated;
revoke all on table public.reserved_seats from anon, authenticated;
revoke all on table public.donation_intents from anon, authenticated;

-- Visitors may only read seat occupancy.
grant select on table public.reserved_seats to anon, authenticated;

-- Re-create the policy safely if script is run again.
drop policy if exists "Public can read occupied seats" on public.reserved_seats;
create policy "Public can read occupied seats"
on public.reserved_seats
for select
to anon, authenticated
using (true);

-- ---------- ATOMIC BOOKING RPC ----------
create or replace function public.create_booking(
  p_full_name text,
  p_phone text,
  p_email text,
  p_seats jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking_id uuid;
  v_seat jsonb;
  v_count integer;
  v_sector text;
  v_row integer;
  v_seat_num integer;
begin
  if p_full_name is null or char_length(trim(p_full_name)) < 2 then
    raise exception 'INVALID_FULL_NAME';
  end if;

  if p_phone is null or char_length(trim(p_phone)) < 5 then
    raise exception 'INVALID_PHONE';
  end if;

  if p_email is null or p_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'INVALID_EMAIL';
  end if;

  if p_seats is null or jsonb_typeof(p_seats) <> 'array' then
    raise exception 'INVALID_SEATS';
  end if;

  v_count := jsonb_array_length(p_seats);
  if v_count < 1 or v_count > 6 then
    raise exception 'SEAT_COUNT_MUST_BE_1_TO_6';
  end if;

  insert into public.bookings (full_name, phone, email)
  values (trim(p_full_name), trim(p_phone), lower(trim(p_email)))
  returning id into v_booking_id;

  for v_seat in select value from jsonb_array_elements(p_seats)
  loop
    v_sector := trim(v_seat->>'sector');
    v_row := (v_seat->>'row')::integer;
    v_seat_num := (v_seat->>'seat')::integer;

    if not (v_sector in ('Сцена', 'Зал', 'Пульт', 'Балкон') or v_sector like 'Балкон %') then
      raise exception 'INVALID_SECTOR';
    end if;

    insert into public.reserved_seats (booking_id, sector, row_num, seat_num)
    values (v_booking_id, v_sector, v_row, v_seat_num);
  end loop;

  return v_booking_id;
exception
  when unique_violation then
    raise exception 'SEAT_ALREADY_BOOKED' using errcode = '23505';
end;
$$;

revoke all on function public.create_booking(text, text, text, jsonb) from public;
grant execute on function public.create_booking(text, text, text, jsonb) to anon, authenticated;

-- ---------- DONATION INTENT RPC ----------
-- Important: this records only that the visitor clicked through.
-- It does NOT prove that DonationAlerts received a payment.
create or replace function public.log_donation_intent(
  p_donor_name text,
  p_amount numeric,
  p_message text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if p_amount is null or p_amount < 50 then
    raise exception 'AMOUNT_TOO_SMALL';
  end if;

  insert into public.donation_intents (donor_name, amount, message)
  values (
    nullif(left(trim(coalesce(p_donor_name, '')), 120), ''),
    p_amount,
    nullif(left(trim(coalesce(p_message, '')), 1000), '')
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.log_donation_intent(text, numeric, text) from public;
grant execute on function public.log_donation_intent(text, numeric, text) to anon, authenticated;

-- ---------- REALTIME ----------
-- Add only the non-sensitive seat table to Realtime.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reserved_seats'
  ) then
    alter publication supabase_realtime add table public.reserved_seats;
  end if;
end $$;

-- ---------- OPTIONAL INDEXES ----------
create index if not exists reserved_seats_booking_id_idx
  on public.reserved_seats (booking_id);
create index if not exists bookings_created_at_idx
  on public.bookings (created_at desc);
create index if not exists donation_intents_created_at_idx
  on public.donation_intents (created_at desc);
